### ISSUE TITLE
Italic or Regular?

### ISSUE THREAD

**Issue by yanone** [docrepair-fonts/lumanosimo-fonts#1]
The reference font is called "Italic", while Lumanosimo is called "Regular". There is some mismatch in the naming table around that that I can fix, but the question is this:

Is it of any importance in the DR project that fonts are of equal technical style? There is already a mismatch between Demi and SemiBold in one of the other fonts, and here again, so I need to clarify this.

My gut decision would be to keep Lumanosimo as Regular since I imagine that font replacements are manually mapped. 

But the real confusion is here: Do users need to activate the Italic style on the reference font? Does it exist as a Roman? Will that cause some confusion with the documents?

**Comment by twardoch** [comment]
It's a good question. Some reference fonts are messy. The Belanosima reference font has weight 600 declared in both Demi and SemiBold. I'll probably switch to the Demi name though. This Italic question is also tricky, because the reference font is "sort of Italic" style but it doesn't have any matching Regular. I'm not sure how well that'll work in the context of Workspace. Let me do some changes there.

**Comment by yanone** [comment]
Whichever direction you go, please note that there was a contradiction in the name table vs. the file name (one representing Italic, one representing Regular). I can fix those, but I need to know which direction we're leaning towards.

**Comment by twardoch** [comment]
I think overall, it'll be safer to do it a proper Regular. A Regular without Italic is safer than Italic without a Regular.
